### ISSUE TITLE
[Bug] Matching ts file with no describe blocks throws `TypeError`

### ISSUE THREAD

**Issue by jtenner** [jtenner/as-pect#25]
```
TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at DefaultTestReporter.onFinish (C:\Users\jtenner\Desktop\projects\as-pect\lib\reporter\DefaultTestReporter.js:149:18)
    at TestContext.run (C:\Users\jtenner\Desktop\projects\as-pect\lib\test\TestContext.js:55:22)
    at C:\Users\jtenner\Desktop\projects\as-pect\lib\cli.js:209:28
    at Object.main (C:\Users\jtenner\Desktop\projects\as-pect\node_modules\assemblyscript\cli\asc.js:700:10)
    at C:\Users\jtenner\Desktop\projects\as-pect\lib\cli.js:176:31
    at Array.forEach (<anonymous>)
    at Object.asp (C:\Users\jtenner\Desktop\projects\as-pect\lib\cli.js:174:42)
    at C:\Users\jtenner\Desktop\projects\as-pect\lib\test.js:13:11
    at C:\Users\jtenner\Desktop\projects\as-pect\lib\test.js:3:17
```

If no describe blocks are in a test suite, the reporter should not even be notified.

**Comment by jtenner** [comment]
Currently waiting on the performance refactor. Will fix this after performance is implemented.
