### ISSUE TITLE
v3.1.2 binary fails

### ISSUE THREAD

**Issue by willemneal** [jtenner/as-pect#271]
When updating as-pect, the lib folder seems to be missing
```
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '../lib/index.js'
Require stack:
- /Users/willem/c/Near-AssemblyScript/near-shell/node_modules/@as-pect/cli/bin/asp
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/willem/c/Near-AssemblyScript/near-shell/node_modules/@as-pect/cli/bin/asp:2:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/willem/c/Near-AssemblyScript/near-shell/node_modules/@as-pect/cli/bin/asp'
  ]
}
```

Above is when I installed into fresh project.  But dependabot is also catching it else where.

**Comment by willemneal** [comment]
Was about to close this, when I ran into another bug:
```
/Users/willem/c/Near-AssemblyScript/near-sdk-as/node_modules/@as-pect/core/lib/reporter/SummaryReporter.js:84
            this.stdout.write(chalk(templateObject_1 || (templateObject_1 = __makeTemplateObject(["{green.bold \u2714 ", "} Pass: ", " / ", " Todo: ", " Time: ", "ms\n"], ["{green.bold \u2714 ",
                        ^

TypeError: Cannot read property 'write' of null
    at SummaryReporter.onFinish (/Users/willem/c/Near-AssemblyScript/near-sdk-as/node_modules/@as-pect/core/lib/reporter/SummaryReporter.js:84:25)
    at TestContext.run (/Users/willem/c/Near-AssemblyScript/near-sdk-as/node_modules/@as-pect/core/lib/test/TestContext.js:217:23)
    at runBinary (/Users/willem/c/Near-AssemblyScript/near-sdk-as/node_modules/@as-pect/cli/lib/run.js:429:24)
    at /Users/willem/c/Near-AssemblyScript/near-sdk-as/node_modules/@as-pect/cli/lib/run.js:626:42
    at Object.main (/Users/willem/c/Near-AssemblyScript/near-sdk-as/node_modules/assemblyscript/cli/asc.js:998:10)
    at /Users/willem/c/Near-AssemblyScript/near-sdk-as/node_modules/@as-pect/cli/lib/run.js:577:17
    at Array.forEach (<anonymous>)
    at run (/Users/willem/c/Near-AssemblyScript/near-sdk-as/node_modules/@as-pect/cli/lib/run.js:575:36)
    at Object.asp (/Users/willem/c/Near-AssemblyScript/near-sdk-as/node_modules/@as-pect/cli/lib/index.js:63:9)
    at Object.<anonymous> (/Users/willem/c/Near-AssemblyScript/near-sdk-as/node_modules/@as-pect/cli/bin/asp:2:28)
```

And to see where it is an issue: https://github.com/near/near-sdk-as/pull/11/checks?check_run_id=517162822

And to try it out it gitpod: need to run `yarn asp:ci`
https://gitpod.io/#https://github.com/near/near-sdk-as/pull/11

**Comment by jtenner** [comment]
Yeah this should be in the documentation. Both of the reporters require stdout to be set.

**Comment by jtenner** [comment]
We can close this issue however, please file a new one.
