### ISSUE TITLE
Skipped test with 'toThrow' assertion crashes the test runner

### ISSUE THREAD

**Issue by ColinEberhardt** [jtenner/as-pect#325]
See:

https://github.com/ColinEberhardt/assemblyscript-regex/blob/as-pect-error/assembly/__spec_tests__/generated.spec.ts

I have a single skipped test:

~~~
xit("line: 1185 - matches ab{3cd against 'ab{3cd'", () => {
  expect(() => new RegExp("ab{3cd")).toThrow();
});
~~~

When I run `npm run asp`, the runner crashes as follows:

~~~
Error [AssertionError]: assertion failed
    at t.assert (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:645440)
    at p.canOverflow (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:229337)
    at T.compileReturnedExpression (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:436254)
    at T.compileFunctionBody (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:407593)
    at T.compileFunction (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:406316)
    at T.compileFunctionExpression (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:501251)
    at T.compileExpression (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:434922)
    at T.compileCallDirect (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:484985)
    at T.compileCallExpression (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:480093)
    at T.compileExpression (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:434709)
    at T.compileCallExpression (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:480026)
    at T.compileExpression (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:434709)
    at T.compileExpressionStatement (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:422187)
    at T.compileStatement (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:418026)
    at T.compileStatements (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:419054)
    at T.compileFunctionBody (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:407392)
    at T.compileFunction (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:406316)
    at T.compileFunctionExpression (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:501251)
    at T.compileExpression (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:434922)
    at T.compileCallDirect (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:484985)
    at T.compileCallExpression (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:480093)
    at T.compileExpression (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:434709)
    at T.compileExpressionStatement (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:422187)
    at T.compileStatement (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:418026)
    at T.compileTopLevelStatement (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:417552)
    at T.compileFile (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:399267)
    at T.compile (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:390142)
    at Object.t.compile (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/dist/assemblyscript.js:7:666244)
    at /Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/cli/asc.js:710:29
    at measure (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/cli/asc.js:1101:3)
    at Object.main (/Users/colineberhardt/Projects/as-regex/node_modules/assemblyscript/cli/asc.js:709:24)
    at /Users/colineberhardt/Projects/as-regex/node_modules/@as-pect/cli/lib/run.js:602:17
    at Array.forEach (<anonymous>)
    at run (/Users/colineberhardt/Projects/as-regex/node_modules/@as-pect/cli/lib/run.js:600:36)
    at Object.asp (/Users/colineberhardt/Projects/as-regex/node_modules/@as-pect/cli/lib/index.js:64:9)
    at Object.<anonymous> (/Users/colineberhardt/Projects/as-regex/node_modules/@as-pect/cli/lib/test.js:2:28)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
~~~

Modifying the skipped test as follows fixes the problem:

~~~
xit("line: 1185 - matches ab{3cd against 'ab{3cd'", () => {
  expect(() => throw new Error("Whoops")).toThrow();
});
~~~

**Comment by jtenner** [comment]
Ah.

```ts
xit("this test gets skipped", () => {});
```

Remove the `x` in that function call. `xit` turns that test into a "todo"

**Comment by ColinEberhardt** [comment]
In this case I want it to be a skipped tests though :-)

**Comment by jtenner** [comment]
Oh you mean this is a compiler error. Sorry, I misread.

```ts
xit("line: 1185 - matches ab{3cd against 'ab{3cd'", () => {
  expect(() => {
    let a = new RegExp("ab{3cd"));
  }).toThrow();
});

```

**Comment by jtenner** [comment]
The function *must* be a `void` function.

**Comment by ColinEberhardt** [comment]
Great - thank you. Would it be possible to generate a more east to understand error in this case?

**Comment by jtenner** [comment]
Yes. This looks like a compiler error. I would file a complaint with assemblyscript about this assertion error.

I also think waiting may be a wise decision because I don't know if this issue is already fixed.

**Comment by jtenner** [comment]
Closing, because this error was related to AssemblyScript and not aspect
