### ISSUE TITLE
console.log fails inside the test

### ISSUE THREAD

**Issue by norrec99** [jtenner/as-pect#336]
```js
describe('Basic test', () => {
  it('should not fail', () => {
    expect(1).toBe(1);
    console.log('testing the test');
    });
});
```

```
[TestFile.ts] node_modules/@as-pect/assembly/assembly/index.ts --debug --binaryFile output.wasm --runtime stub --baseDir /home/cagatay/code/norrec99/paw --runPasses inlining,dce --config /home/cagatay/code/norrec99/paw/node_modules/near-sdk-as/asp.asconfig.json --explicitStart --use ASC_RTRACE=1 --exportTable --importMemory --transform /home/cagatay/code/norrec99/paw/node_modules/@as-pect/core/lib/transform/index.js

/home/cagatay/code/norrec99/paw/node_modules/assemblyscript/lib/loader/umd/index.js:379
    const instance = new WebAssembly.Instance(module, imports);
                     ^

TypeError: WebAssembly.Instance(): Import #16 module="wasi_snapshot_preview1" error: module is not an object or function
    at instantiateSync (/home/cagatay/code/norrec99/paw/node_modules/assemblyscript/lib/loader/umd/index.js:379:22)
    at createImports (/home/cagatay/code/norrec99/paw/node_modules/near-sdk-as/imports.js:11:10)
    at runBinary (/home/cagatay/code/norrec99/paw/node_modules/@as-pect/cli/lib/run.js:423:26)
    at /home/cagatay/code/norrec99/paw/node_modules/@as-pect/cli/lib/run.js:638:42
    at wrappedCallback (/home/cagatay/code/norrec99/paw/node_modules/assemblyscript/cli/asc.js:436:14)
    at Object.main (/home/cagatay/code/norrec99/paw/node_modules/assemblyscript/cli/asc.js:1058:10)
    at /home/cagatay/code/norrec99/paw/node_modules/@as-pect/cli/lib/run.js:589:17
    at Array.forEach (<anonymous>)
    at run (/home/cagatay/code/norrec99/paw/node_modules/@as-pect/cli/lib/run.js:587:36)
    at Object.asp (/home/cagatay/code/norrec99/paw/node_modules/@as-pect/cli/lib/index.js:64:9)
    at Object.<anonymous> (/home/cagatay/code/norrec99/paw/node_modules/@as-pect/cli/lib/test.js:2:28)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
error Command failed with exit code 1.
```

**Comment by jtenner** [comment]
Hello! Sorry for the late reply.

```
TypeError: WebAssembly.Instance(): Import #16 module="wasi_snapshot_preview1" error: module is not an object or function
```

It does appear you might require using `Wasi` here.

**Comment by willemneal** [comment]
Also if you aren't targeting Wasi, the `log` method provided by as-pect can be used anywhere since it's global when compiling tests.

**Comment by jtenner** [comment]
I believe that this will require using the `"wasi": {}` `aspect.config.js` property.

**Comment by norrec99** [comment]
Yes, thank you.

**Comment by winstonwolff** [comment]
Regarding 
> I believe that this will require using the "wasi": {} aspect.config.js property.
can you give more details or an example on how to add this property to as-pect.config.js? Which section does it go in?
