### ISSUE TITLE
Assertion Error is not very informative

### ISSUE THREAD

**Issue by willemneal** [jtenner/as-pect#43]
I just got the following error and I think this might be an issue with AssemblyScript, but I thought I'd put it here:
```
Compiling: packages/ash/assembly/__tests__/cat.spec.ts 1 / 4
There was a compilation error when trying to create the wasm binary for file: packages/ash/assembly/__tests__/cat.spec.ts.
{ AssertionError: assertion failed
    at r.assert (/Users/willem/Research/wasmos/node_modules/assemblyscript/dist/assemblyscript.js:2:134139)
    at r.compileAssignment (/Users/willem/Research/wasmos/node_modules/assemblyscript/dist/assemblyscript.js:1:235120)
    at r.compileBinaryExpression (/Users/willem/Research/wasmos/node_modules/assemblyscript/dist/assemblyscript.js:1:217088)
    at r.compileExpression (/Users/willem/Research/wasmos/node_modules/assemblyscript/dist/assemblyscript.js:1:205221)
    at r.compileExpressionStatement (/Users/willem/Research/wasmos/node_modules/assemblyscript/dist/assemblyscript.js:1:196111)
    at r.compileStatement (/Users/willem/Research/wasmos/node_modules/assemblyscript/dist/assemblyscript.js:1:192940)
    at r.compileStatements (/Users/willem/Research/wasmos/node_modules/assemblyscript/dist/assemblyscript.js:1:193921)
    at r.compileFunctionBody (/Users/willem/Research/wasmos/node_modules/assemblyscript/dist/assemblyscript.js:1:186103)
    at r.compileFunction (/Users/willem/Research/wasmos/node_modules/assemblyscript/dist/assemblyscript.js:1:188222)
    at r.compileFunctionExpression (/Users/willem/Research/wasmos/node_modules/assemblyscript/dist/assemblyscript.js:1:256171) message: 'assertion failed' }
```
What assertion??

**Comment by jtenner** [comment]
Yeah. This is clearly a compiler error. You should file with the assemblyscript repo. `as-pect` currently requires the latest version of the assemblyscript compiler, and I've fixed many errors like this by switching to the latest version, and doing a fresh install of everything.

This looks like an assignmentExpression does not match an assertion in this file/function: https://github.com/AssemblyScript/assemblyscript/blob/master/src/compiler.ts#L4634

**Comment by jtenner** [comment]
Once runtime hits, this error might go away. I assume this is also no longer an issue?
