### ISSUE TITLE
Parse error on import statement (am I doing it right?)

### ISSUE THREAD

**Issue by trusktr** [jtenner/as-pect#71]
How do I import code into my test file?

I have the following `Size.spec.ts` file:

```ts
import Size from './Size' // ./Size.ts

describe('Size class', (): void => {
	describe('#.add', (): void => {
		it('should add another Size to this Size', (): void => {
			let s = new Size(20.1, 30.2)
			const other = new Size(40.3, 50.4)

			s.add(other)

			assertDimensions(s, 60.4, 80.6)
			expect<i32>(19 + 23).toBe(42, '42 is the meaning of life.')
		})
	})
})

function assertDimensions(s: Size, width: f64, height: f64): void {
	expect<f64>(s.width).toBe(width)
	expect<f64>(s.height).toBe(height)
}
```

When I run `asp`, I get 

```
[Log] using configuration /Users/trusktr/src/infamous+glas/as-pect.config.js
[Log] Including files: src/as/**/*.spec.ts

ERROR TS1141: String literal expected.

 import Size from './Size'
 ~~~~~~
 in src/as/glas/Size.spec.ts(1,0)

There was a compilation error when trying to create the wasm binary for file: src/as/glas/Size.spec.ts.

Error: Parse error
    at parseBacklog (/Users/trusktr/src/infamous+glas/node_modules/as-pect/node_modules/assemblyscript/cli/asc.js:363:23)
    at Object.main (/Users/trusktr/src/infamous+glas/node_modules/as-pect/node_modules/assemblyscript/cli/asc.js:390:16)
    at /Users/trusktr/src/infamous+glas/node_modules/as-pect/lib/cli/run.js:114:27
    at Array.forEach (<anonymous>)
    at Object.run (/Users/trusktr/src/infamous+glas/node_modules/as-pect/lib/cli/run.js:113:36)
    at Object.asp (/Users/trusktr/src/infamous+glas/node_modules/as-pect/lib/cli/index.js:61:19)
    at Object.<anonymous> (/Users/trusktr/src/infamous+glas/node_modules/as-pect/bin/asp:2:32)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
```

**Comment by trusktr** [comment]
Here's a repro: https://github.com/infamous/glas/pull/1

**Comment by trusktr** [comment]
I changed

```ts
import Size from './Size'
```

to

```ts
import {Size} from './Size'
```

And that caused the error to go away. But then I got an error in `Size.ts` on the line

```ts
export default Size
```

So I changed it to 

```ts
export {Size}
```

and it worked.

Looks like default exports aren't supported yet.

**Comment by jtenner** [comment]
I didn't get a chance to take a look yet. I'll be busy today, but that's great if you solved the problem. Is this on the dev assemblyscript branch?

**Comment by jtenner** [comment]
This sounds like an assemblyscript error to be honest.

**Comment by trusktr** [comment]
Yeah, I'd say it's an AS problem (wither default exports broke, or they just aren't supported yet).
